name: "Staging Release - Step 3: Release to CDN and Synchronize Branches"

on:
    workflow_dispatch:

jobs:
    synchronize-branches:
      name: Synchronize SDK to all branches
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
        GIT_AUTHOR_NAME: mparticle-automation
        GIT_AUTHOR_EMAIL: developers@mparticle.com
        GIT_COMMITTER_NAME: mparticle-automation
        GIT_COMMITTER_EMAIL: developers@mparticle.com

      steps:
        - name: Checkout staging branch
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
            repository: ${{ github.repository }}
            token: ${{ secrets.MP_SEMANTIC_RELEASE_BOT }}
            ref: staging

        - name: Push release commits to development
          run: |
            git push origin HEAD:development
        
        # We will eventually replace master with main
        - name: Push release commits to main and master
          run: |
            git push origin HEAD:master
            git push origin HEAD:main

        - name: Push release commits to Release Order Branches
          run: |
            git push origin HEAD:release-order-a
            git push origin HEAD:release-order-b
            git push origin HEAD:release-order-c